name: Deploy

on:
  push:
    paths:
      - "**.js"
      - "**.ts"
      - "**.json"
      - "**.mdx?"
  workflow_dispatch:

env:
  NODE_ENV: production 

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 📁 Checkout
        uses: actions/checkout@v2

      - name: 📦 Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: dreamtime-www
        with:
          path: |
            node_modules
            !node_modules/.cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: 🧰 Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true

      - name: 👨🏻‍💻 Install dependencies
        run: yarn install

      - name: 🏗️ Build
        run: yarn run build

      - name: 🚀 Deploy
        run: yarn run deploy
        timeout-minutes: 20
        env:
          DEPLOY_PINATA_TOKEN: ${{ secrets.DEPLOY_PINATA_TOKEN }}
          DEPLOY_DREAMLINKCLUSTER_USERNAME: dreamnet
          DEPLOY_DREAMLINKCLUSTER_PASSWORD: ${{ secrets.DEPLOY_DREAMLINKCLUSTER_PASSWORD }}
          DEPLOY_CLOUDFLARE_EMAIL: ${{ secrets.DEPLOY_CLOUDFLARE_EMAIL }}
          DEPLOY_CLOUDFLARE_KEY: ${{ secrets.DEPLOY_CLOUDFLARE_KEY }}
          DEPLOY_CLOUDFLARE_ZONE: dreamtime.tech
          DEPLOY_CLOUDFLARE_RECORD: _dnslink.www
