name: Build

on:
  push:
    paths:
      - "**.js"
      - "**.ts"
      - "**.json"
      - "**.mdx?"

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Deploy
        run: yarn run deploy
        timeout-minutes: 20
        env:
          DEPLOY_PINATA_TOKEN: ${{ secrets.DEPLOY_PINATA_TOKEN }}
          DEPLOY_DREAMLINKCLUSTER_USERNAME: dreamnet
          DEPLOY_DREAMLINKCLUSTER_PASSWORD: ${{ secrets.DEPLOY_DREAMLINKCLUSTER_PASSWORD }}
          DEPLOY_CLOUDFLARE_EMAIL: ${{ secrets.DEPLOY_CLOUDFLARE_EMAIL }}
          DEPLOY_CLOUDFLARE_KEY: ${{ secrets.DEPLOY_CLOUDFLARE_KEY }}
          DEPLOY_CLOUDFLARE_ZONE: dreamtime.tech
          DEPLOY_CLOUDFLARE_RECORD: _dnslink.www
